# Generated by Django 4.1.4 on 2023-02-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizza",
            name="topping2",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pizza",
            name="topping1",
            field=models.CharField(max_length=20),
        ),
    ]
